spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pinyougoudb?characterEncoding=utf-8
    username: root
    password: root

dubbo:
  application:
    name: zhipeng-pyg-service
#    qos-port: 22222
#    qos-enable: true
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
    status: server
  scan:
    base-packages: cn.net.zhipeng.service
#  monitor:
#    protocol: registry

mybatis:
  #  configuration:
  #    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/SqlMapConfig.xml
