server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pinyougoudb?characterEncoding=utf-8
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#security:
    ##    user:
    ##      password: 123456
  servlet:
    multipart:
      max-file-size: 5MB

dubbo:
  application:
    name: zhipeng-pyg-web
    ## Legacy QOS Config
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
#  monitor:
#    protocol: registry

#debug: true

zhipeng:
  security:
    qq:
      app-id:
      app-secret:
    sms:
      accessKeyId:
      accessKeySecret:
      templateCode:

